// LOGIN
export const LOGIN_START      = 'LOGIN_START';
export const LOGIN_SUCCESS    = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE    = 'LOGIN_FAILURE';
export const RESET_LOGIN      = 'RESET_LOGIN';

// LOGOUT
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// COURSE
export const COURSE_START = 'COURSE_START';
export const COURSE_SUCCESS = 'COURSE_SUCCESS';
export const COURSE_FAILURE = 'COURSE_FAILURE';

// LESSONS
export const LESSONS_START = 'LESSONS_START';
export const LESSONS_SUCCESS = 'LESSONS_SUCCESS';
export const LESSONS_FAILURE = 'LESSONS_FAILURE';

// LESSON
export const LESSON_START = 'LESSON_START';
export const LESSON_SUCCESS = 'LESSON_SUCCESS';
export const LESSON_FAILURE = 'LESSON_FAILURE';

// PROFILE
export const PROFILE_START   = 'PROFILE_START';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';

// LEVEL
export const LEVEL_START   = 'LEVEL_START';
export const LEVEL_SUCCESS = 'LEVEL_SUCCESS';
export const LEVEL_FAILURE = 'LEVEL_FAILURE';

// LEVEL MOBILE
export const LEVEL_MB_START   = 'LEVEL_MB_START';
export const LEVEL_MB_SUCCESS = 'LEVEL_MB_SUCCESS';
export const LEVEL_MB_FAILURE = 'LEVEL_MB_FAILURE';

// RESULT
export const RESULT_POST_START   = 'RESULT_POST_START';
export const RESULT_POST_SUCCESS = 'RESULT_POST_SUCCESS';
export const RESULT_POST_FAILURE = 'RESULT_POST_FAILURE';

export const RESULT_GET_START   = 'RESULT_GET_START';
export const RESULT_GET_SUCCESS = 'RESULT_GET_SUCCESS';
export const RESULT_GET_FAILURE = 'RESULT_GET_FAILURE';